// CONFIG OF THE TOPOLOGY

#define MAX_LENGTH 500
#define MESSAGE_SIZE 2500
#define NB_BBU 2
#define NB_COLLISIONS 3
#define NB_ROUTES_PER_FLOW 3
#define PROBA 0.5

// CONFIG OF THE SIMULATION FOR ALGORITHMS WITHOUT WAITING TIME
#define LOAD_MIN 0.5
#define LOAD_MAX 1
#define LOAD_GAP 0.1


// CONFIG OF THE SIMULATIONS FOR ALGORITHMS WITH WAITING TIME
#define MARGIN_MIN 0
#define MARGIN_MAX 15000
#define MARGIN_GAP 1000
#define STANDARD_LOAD 0.7



#define NB_SIMULS 100
